global:
  resolve_timeout: 5m

route:
  group_by: ['...']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 8h
  receiver: 'vo_rabbit_monitor'
  routes:
    - receiver: vo_email
      match:
        alertname: vo_rabbit_monitor:down
    - receiver: vo_rabbit_monitor
      match_re:
        alertname: rabbitmq:.*

receivers:
- name: 'vo_rabbit_monitor'
  webhook_configs:
  - url: 'http://10.0.1.52:8080/rabbit/alert-hook'
- name: 'vo_email'
  email_configs:
  - smarthost: smtp.exmail.qq.com:587
    auth_username: 'internal_info@voyageone.cn'
    auth_password: 'VOdevops2019'
    to: 'johny.song@voyageone.cn'
    from: 'internal_info@voyageone.cn'
    hello: 'erp_rabbitmq_alert'

inhibit_rules:
  - source_match:
      level: 'FATAL'
    target_match:
      level: 'WARN'
    equal: ['alertname', 'instance', 'cluster']
  - source_match:
      level: 'FORCE_RESTART'
    target_match:
      level: 'FATAL'
    equal: ['alertname', 'instance', 'cluster']
  - source_match:
      level: 'WARN'
    target_match:
      level: 'INFO'
    equal: ['alertname', 'instance', 'cluster']
