groups:
  - name: rabbitmq
    interval: 1m
    rules:
      - alert: rabbitmq:cpu_usage_exceeds_95_10min
        expr: avg_over_time(rabbitmq:cup_usage_percent[10m]) > 95
        labels:
          level: INFO
        annotations:
          summary: rabbitmq节点CPU使用率10分钟内平均大于95%，请关注

      - alert: rabbitmq:memory_usage_exceeds_60_3min
        expr: avg_over_time(rabbitmq:memory_usage_percent[3m]) > 60
        labels:
          level: INFO
        annotations:
          summary: rabbitmq节点内存使用率3分钟内平均大于60%，请关注

      - alert: rabbitmq:custom_warn_1
        expr: rabbitmq:cpu_usage_percent > 95 and rabbitmq:memory_usage_percent > 70 and delta(rabbitmq:memory_usage_percent[1m]) > 10
        labels:
          level: WARN
        annotations:
          summary: |
            rabbitmq节点内存使用率当前大于95%，且CPU使用率当前大于70%，且1分钟内内存使用率上升超过10%。
            根据以往经验，这通常是一个rabbitmq内存飙升并最终崩溃的表现，请尽快查看rabbit服务器情况！

      - alert: rabbitmq:custom_fatal_1
        expr: avg_over_time(rabbitmq:cup_usage_percent[1m]) > 95 and rabbitmq:memory_usage_percent > 95 and delta(rabbitmq:memory_usage_percent[1m]) > 10
        labels:
          level: FATAL
        annotations:
          summary: |
            rabbitmq节点CPU使用率1分钟内平均大于95%，且内存使用率当前大于95%，且1分钟内内存使用率上升超过10%。
            根据以往经验，这通常是一个rabbitmq内存飙升并即将崩溃的表现，请立即查看rabbit服务器情况！

      - alert: rabbitmq:mem_high_watermeter_alarm
        expr: vorabbit_mem_alarm == 1
        labels:
          level: FATAL
        annotations:
          summary: rabbitmq节点触发内存高水位警报，消息生产可能被阻塞

      - alert: rabbitmq:disk_free_alarm
        expr: vorabbit_disk_free_alarm == 1
        labels:
          level: FATAL
        annotations:
          summary: rabbitmq节点触发磁盘可用空间不足警报，消息生产可能被阻塞

      - alert: rabbitmq:publish_msq_failed
        expr: vorabbit_publish_msq_ok == 0
        labels:
          level: WARN
        annotations:
          summary: rabbitmq生产者发布消息失败，消息生产可能被rabbitmq阻塞，或者rabbitmq崩溃
        
      - alert: rabbitmq:ack_msq_failed
        expr: vorabbit_ack_msq_ok == 0
        labels:
          level: WARN
        annotations:
          summary: rabbitmq消费者获取消息失败，rabbitmq可能崩溃

      - alert: rabbitmq:management_api_failed
        expr: vorabbit_up == 0
        labels:
          level: FORCE_RESTART
        annotations:
          summary: 节点rabbitmq崩溃，如被设置自动重启，则触发重启rabbitmq
      
      - alert: rabbitmq:node_resource_exhausted
        expr: avg_over_time(rabbitmq:cup_usage_percent[3m]) > 98 and avg_over_time(rabbitmq:memory_usage_percent[3m]) > 98
        labels:
          level: FORCE_RESTART
        annotations:
          summary: |
            rabbitmq节点CPU和内存使用率3分钟内都平均大于98%, 服务器资源耗尽，非常紧急
            如被设置自动重启，则触发重启rabbitmq

      - alert: vo_rabbit_monitor:down
        expr: up{job="vo_rabbit_monitor"} == 0
        labels:
          level: WARN
        annotations:
          summary: rabbitmq监控服务vo_rabbit_monitor进程停止, 请检查
