global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rabbit_node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['rabbit:9100']
        labels:
          cluster: 'rabbitmq'
          node: 'rabbit'
  - job_name: 'vo_rabbit_monitor'
    scrape_interval: 10s
    metrics_path: '/rabbit/metrics'
    static_configs:
      - targets: ['10.0.1.52:8080']
rule_files:
  - /etc/prometheus/record_rules.yml
  - /etc/prometheus/alert_rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['127.0.0.1:29093']
